### ISSUE TITLE
rbenv install issue

### ISSUE THREAD

**Issue by douglasrlee** [noonat/docker-rbenv-nodenv#4]
Since the latest update our ruby builds have been failing with this error:
```
The Ruby openssl extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Try running `apt-get install -y libssl-dev` to fetch missing dependencies.

Configure options used:
  --prefix=/root/.rbenv/versions/2.3.2
  LDFLAGS=-L/root/.rbenv/versions/2.3.2/lib 
  CPPFLAGS=-I/root/.rbenv/versions/2.3.2/include
```
Here is our docker file:
```
FROM noonat/rbenv-nodenv

RUN apt-get update
RUN apt-get install -yq --reinstall nodejs wget unzip openssh-server libpq-dev netcat libssl-dev

ARG PUBLIC_KEY
ARG PRIVATE_KEY

RUN mkdir -p ${HOME}/.ssh
RUN echo "${PRIVATE_KEY}" >> ${HOME}/.ssh/id_rsa
RUN echo "${PUBLIC_KEY}" >> ${HOME}/.ssh/id_rsa.pub
RUN echo "Host github.com\n\tStrictHostKeyChecking no\n" >> ${HOME}/.ssh/config
RUN chmod 600 ${HOME}/.ssh/id_rsa

RUN mkdir /app
WORKDIR /app

RUN cd /root/.rbenv/plugins/ruby-build && git pull && cd -
COPY .ruby-version ./
RUN rbenv install

ENV RAILS_ENV test

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install -j20

COPY . ./
```

We are trying to install `2.3.2`.

**Comment by douglasrlee** [comment]
I upgraded to `2.5.1` and it works but this is still an issue on the older versions. It has something to do with using an older version of openssl.

**Comment by noonat** [comment]
Apologies that the updates broke things for you! I'm glad you were able to get it working with a newer version.

It appears, as you say, that this is due to needing an older version of OpenSSL. The ruby-build project says that Ruby versions < 2.4 are not compatible with OpenSSL 1.1 and require an older version instead. (See: https://github.com/rbenv/ruby-build/issues/1199) Unfortunately, as the two SSL packages are mutually exclusive on Debian, it's something individuals using an older version of Ruby will need to do in their Dockerfiles themselves.

You can install that in your example Dockerfile by changing libssl-dev to libssl1.0-dev in your apt-get install line. I tested that out locally and the image builds. I'll make a note in the readme for anyone else that runs into this in the future.
